In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
credited_card_df = pd.read_csv('creditcard.csv')

In [6]:
credited_card_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
credited_card_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [8]:
credited_card_df.shape

(284807, 31)

In [9]:
credited_card_df['Class']

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [10]:
credited_card_df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [11]:
credited_card_df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,3.918649e-15,5.682686e-16,-8.761736e-15,2.811118e-15,-1.552103e-15,2.040130e-15,-1.698953e-15,-1.893285e-16,-3.147640e-15,...,1.473120e-16,8.042109e-16,5.282512e-16,4.456271e-15,1.426896e-15,1.701640e-15,-3.662252e-16,-1.217809e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [12]:
legit = credited_card_df[credited_card_df.Class == 0]
fraud = credited_card_df[credited_card_df['Class']== 1]

In [13]:
legit['Class'].value_counts()

0    284315
Name: Class, dtype: int64

In [14]:
fraud.Class.value_counts()

1    492
Name: Class, dtype: int64

In [30]:
legit_sample = legit.sample(n= len(fraud), random_state= 2)

In [29]:
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
188671,128077.0,-3.288944,-4.809848,-1.231524,6.041078,-1.948400,1.772856,2.177367,0.561664,-1.859951,...,1.352295,0.869342,2.760665,-0.514612,0.114622,0.531044,-0.533325,-0.548096,1206.14,0
190546,128878.0,2.020493,-1.000658,-1.039495,-0.453275,-0.737034,-0.433760,-0.587955,-0.148476,-0.491796,...,0.024865,0.619987,-0.041074,-0.264674,-0.025601,0.910031,-0.051887,-0.063195,67.95,0
46318,42728.0,0.883694,-0.761362,0.928801,1.389779,-0.730351,1.228938,-0.771123,0.432439,1.196648,...,-0.036445,-0.104183,-0.321204,-0.812608,0.547630,-0.273658,0.055533,0.039590,150.00,0
267636,162855.0,-0.072377,0.735400,-2.211240,-2.153156,3.556343,2.781633,1.142571,0.602748,-0.561615,...,0.256899,0.796234,-0.159167,0.752505,-0.263957,0.108374,0.406915,0.263924,24.00,0
189610,128481.0,-0.264285,0.990040,-0.643148,-0.984799,0.813840,0.033159,0.536661,0.483326,-0.368426,...,-0.246360,-0.708310,-0.024761,-1.457310,-0.325381,0.213825,0.115022,0.010990,14.28,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146264,87572.0,-3.264604,2.715905,-1.549820,-2.995830,0.708843,0.101805,-0.885264,-9.511777,1.752832,...,8.371677,-1.954384,1.078571,-0.096610,-0.144411,0.521326,0.457437,-0.175061,4.00,0
265091,161736.0,1.860578,0.455548,0.304742,3.806008,-0.125531,0.204845,-0.308351,0.040213,-0.626641,...,-0.180278,-0.447077,0.431686,-0.074439,-0.544677,-0.381645,0.020363,-0.022831,5.55,0
182736,125528.0,1.879695,-0.669803,-0.064178,0.298964,-0.870328,0.193742,-1.036643,0.328696,1.484790,...,0.117147,0.345893,0.293848,0.717432,-0.455297,-0.468292,0.036596,-0.027390,30.24,0
2371,1921.0,-0.899027,-0.216091,1.707740,0.069804,-2.140060,0.510716,1.227899,-0.126151,0.476636,...,-0.029403,0.110562,0.196984,0.475584,-0.584561,1.021553,0.123096,0.046671,370.76,0
24400,33215.0,1.083359,-0.733445,0.791842,0.481862,-1.135245,0.217980,-0.858432,0.278347,-0.809759,...,-0.140822,-0.134466,-0.011760,-0.054033,0.206405,-0.289459,0.058411,0.033011,79.00,0

In [17]:
credited_card_df = pd.concat([legit_sample, fraud], axis = 0)

In [18]:
credited_card_df.shape

(984, 31)

In [19]:
credited_card_df['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [20]:
credited_card_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94694.201220,0.138447,-0.060420,0.020544,-0.008910,0.034177,-0.083342,0.075980,-0.035586,-0.074936,...,-0.004284,-0.006840,0.007303,-0.017343,0.05214,-0.006031,-0.007944,-0.001290,-0.012779,93.223638
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

In [21]:
x = credited_card_df.drop('Class', axis = 1)
y = credited_card_df['Class']

In [22]:
x.shape

(984, 30)

In [23]:
y.shape

(984,)

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size =0.2, 
                                                   stratify=y, 
                                                   random_state=2)

In [25]:
model = LogisticRegression()
model.fit(x_train, y_train)
ypred = model.predict(x_test)

In [26]:
accuracy_score(ypred, y_test)

0.934010152284264

In [34]:
pip install streamlit

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: streamlit in c:\users\ngquo\appdata\roaming\python\python39\site-packages (1.25.0)
Requirement already satisfied: pympler<2,>=0.9 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (1.0.1)
Requirement already satisfied: watchdog>=2.1.5 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.1.6)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (5.3.1)
Requirement already satisfied: numpy<2,>=1.19.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (1.21.5)
Requirement already satisfied: altair<6,>=4.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (8.2.2)
Requirement already satisfied: click<9,>=7.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (8.0.4)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: pillow<10,>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (9.2.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (6.1)
Requirement already satisfied: typing-extensions<5,>=4.1.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.3.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: requests<3,>=2.18 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.28.1)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (1.4.4)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (13.5.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (3.1.32)
Requirement already satisfied: pyarrow>=6.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (12.0.1)
Requirement already satisfied: validators<1,>=0.2 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (0.20.0)
Requirement already satisfied: python-dateutil<3,>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (2.8.2)
Requirement already satisfied: packaging<24,>=16.8 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (21.3)
Requirement already satisfied: protobuf<5,>=3.20 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (4.24.0)
Requirement already satisfied: tzlocal<5,>=1.1 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (4.3.1)
Requirement already satisfied: importlib-metadata<7,>=1.4 in c:\programdata\anaconda3\lib\site-packages (from streamlit) (4.11.3)
Requirement already satisfied: pydeck<1,>=0.8 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: toolz in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (0.11.2)
Requirement already satisfied: jsonschema>=3.0 in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.16.0)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (2.11.3)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.10)
Requirement already satisfied: zipp>=0.5 in c:\programdata\anaconda3\lib\site-packages (from importlib-metadata<7,>=1.4->streamlit) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging<24,>=16.8->streamlit) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2022.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.3->streamlit) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.18->streamlit) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.18->streamlit) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.18->streamlit) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3,>=2.18->streamlit) (1.26.11)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from rich<14,>=10.14.0->streamlit) (2.16.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pytz-deprecation-shim in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from tzlocal<5,>=1.1->streamlit) (0.1.0.post0)
Requirement already satisfied: tzdata in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from tzlocal<5,>=1.1->streamlit) (2023.3)
Requirement already satisfied: decorator>=3.4.0 in c:\programdata\anaconda3\lib\site-packages (from validators<1,>=0.2->streamlit) (5.1.1)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.0.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.18.0)
Requirement already satisfied: attrs>=17.4.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (21.4.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\ngquo\appdata\roaming\python\python39\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)

In [31]:
# evaluate model performance
train_acc = accuracy_score(model.predict(x_train), y_train)
test_acc =  accuracy_score(model.predict(x_test), y_test)

In [32]:
train_acc

0.9440914866581956

In [33]:
test_acc

0.934010152284264

In [36]:
import streamlit as st

In [39]:
# web app
st.title("Credit Card Fraud Detection Model")
input_df = st.text_input('Enter All required Features Values')
input_df_splited = input_df.split(',')

submit = st.button("Submit")

if submit: 
    features = np.asarray(input_df_splited, dtype = np.float64)
    prediction = model.predict(features.reshape(1,-1))
    
    if prediction[0] == 0:
        st.write("Legitimate Transaction")
    else:
        st.write("Fradulant Transaction")

In [46]:
streamlit run "Credit Card Fraud Detection V2.py"

SyntaxError: invalid syntax (2615690450.py, line 1)